# Generated by Django 5.2.6 on 2026-01-19 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_options_alter_order_customer_address_and_more'),
    ]

    operations = [
    ]
